/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package one.chest.polymorph.processor;

import org.junit.jupiter.api.Test;

class LibraryTest {
    @Test
    void testSomeLibraryMethod() {
//        Library classUnderTest = new Library();
//        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'");
    }
}
